
version: 2

jobs:

  build:
    docker:
      - image: circleci/openjdk:latest
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - restore_cache:
          keys:
            - gradle
      - checkout
      - run: ./mvnw clean package -Ppmd,checkstyle,spotbugs

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
