
version: 2

jobs:

  build:

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    parallelism: 3

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run: ./gradlew clean build

  deploy:

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    parallelism: 3

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run: ./gradlew clean build bintrayUpload


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - development
                - master
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
