
version: 2

jobs:

  build:

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    parallelism: 3

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    brances:
      only:
        - master
        - development
    steps:
      - checkout
      - run: ./gradlew clean build
